import assert from "node:assert/strict";

import { TTAssistEngine } from "../js/tt/assist-engine.js";
import { initTypeSystem } from "../js/tt/initial.js";

const engine = new TTAssistEngine();
engine.configure({
    unlockedTypes: [...new Set(initTypeSystem().map(rule => rule.id))],
    inferDisplayMode: "_",
    timeout: 30_000,
    language: "zh"
});

const options = {
    disableMultipleApply: false,
    disableDestructConds: false,
    disableDestructEq: false
};

// Reproduce issue #25: the branch equality generated by `destruct` is
// simplified and then used by `rw`; the completed proof must remain valid
// when qed validates the serialized term against the original theorem.
const originalLog = console.log;
try {
    console.log = () => { };
    engine.start("Πx:nat,eq (add 0 x) x", options);
    for (const command of ["intro x", "destruct x", "rfl", "simpl", "rw x_", "rfl"]) {
        engine.apply(command);
    }
} finally {
    console.log = originalLog;
}

const result = engine.qed();
assert.equal(result.theorem, "(Πx:nat,eq (add 0 x) x)");
const checked = engine.engine.check(`${result.proof}:${result.theorem}`);
assert.equal(checked.ok, true, checked.error ?? "issue #25 proof failed Core validation");

console.log("GitHub issue #25 zero-add qed regression passed");
