import { AST, ASTMgr } from "./astmgr.js";
import { FSCmd } from "./cmd.js";
import { iniSysFnList, initFormalSystem } from "./initial.js";
import { DEFERRED_ASSISTANT_STEP, Deduction, DeductionStep, FormalSystem } from "./formalsystem.js";
import { TR } from "../lang.js";
import { ProofScriptEditor, scriptThroughCaret } from "../proof-editor.js";
import { ListDragger } from "./itemdragger.js";
import { RuleTree } from "./metarule.js";
import { InferencePage, SerializedInferencePages } from "./inference-pages.js";
import {
    InferenceProofAssistant,
    InferenceProofQedResult,
    InferenceProofSnapshot
} from "./proof-assistant.js";
import { SavesParser } from "./savesparser.js";
import { migrateInferenceProofCommand, migrateInferenceProofHistory } from "./proof-syntax.js";
import {
    InferenceWorkerClient,
    InferenceWorkerResult,
    InferenceWorkerTarget
} from "./inference-worker-client.js";
const astmgr = new ASTMgr();
const inferenceProofTextModeStorageKey = "deductrium-fs-proof-text-mode";

type PersistedInferenceProofDraft = {
    theorem: AST;
    history: string[];
    script?: string;
    textMode?: boolean;
};

export class FSGui {
    skipRendering = true;
    readonly creative: boolean;
    formalSystem = new FormalSystem();
    actionInput: HTMLInputElement;
    hintText: HTMLDivElement;
    omitNfFn = false;
    italicItem = false;
    propositionList: HTMLOListElement;
    pageTabs: HTMLElement | null = null;
    /** Page state is owned by the formal-system model; the GUI only renders it. */
    get pageStore() { return this.formalSystem.inferencePages; }
    set pageStore(value: FormalSystem["inferencePages"]) { this.formalSystem.inferencePages = value; }
    deductionList: HTMLOListElement;
    metaRuleList: HTMLOListElement;
    sysFnList: HTMLOListElement;
    sysfns: [AST, string, string][];
    cmdBtns: NodeListOf<HTMLButtonElement>;
    displayDs = new Set();
    deductions: string[] = [];
    metarules: string[] = [];
    autoGenerateDeduction = true;
    unlockedMacro = false;
    unlockedHyp = false;
    unlockedRename = false;
    unlockedFolder = false;
    unlockedSysRulePanel = false;
    enableMIFFT_RP = false;
    /** The deduction-layer assistant is intentionally separate from TT tactics. */
    private inferenceProofAssistant: InferenceProofAssistant | null = null;
    private inferenceProofSnapshot: InferenceProofSnapshot | null = null;
    private inferenceProofPageId: string | null = null;
    private inferenceProofBusy = false;
    private inferenceProofTextMode = false;
    private inferenceProofTextModePreference = false;
    private inferenceProofScript = "";
    private inferenceProofScriptDirty = false;
    private inferenceProofScriptEditor: ProofScriptEditor | null = null;
    private inferenceProofTextReplayTimer: number | null = null;
    private inferenceWorkerClient: InferenceWorkerClient | null = null;
    onStateChange = () => { };
    onchangeOmitNF = () => { };
    draggerD = new ListDragger(document.getElementById("deduct-list"));
    draggerM = new ListDragger(document.getElementById("meta-list"));
    draggerP = new ListDragger(document.getElementById("prop-list"));

    isMobile = /Mobi|Android|iPhone/i.test(navigator.userAgent);
    cmd: FSCmd;
    constructor(
        propositionList: HTMLOListElement, deductionList: HTMLOListElement, metaRuleList: HTMLOListElement, sysFnList: HTMLOListElement,
        actionInput: HTMLInputElement, hintText: HTMLDivElement, displayPLayerSelect: HTMLSelectElement,
        cmdBtns: NodeListOf<HTMLButtonElement>, creative: boolean, skipRendering: boolean
    ) {
        this.creative = creative;
        this.skipRendering = skipRendering;
        this.propositionList = propositionList;
        this.pageTabs = document.getElementById("inference-page-tabs");
        this.metaRuleList = metaRuleList;
        this.deductionList = deductionList;
        this.sysFnList = sysFnList;
        this.actionInput = actionInput;
        this.hintText = hintText;
        this.cmdBtns = cmdBtns;
        this.cmd = new FSCmd(this);
        const { fs, arrD } = initFormalSystem(creative);
        this.formalSystem = fs;
        try {
            this.inferenceProofTextModePreference = window.localStorage.getItem(inferenceProofTextModeStorageKey) === "1";
        } catch { }
        this.inferenceProofTextMode = this.inferenceProofTextModePreference;
        this.deductions = arrD;
        this.sysfns = iniSysFnList();
        this.initInferenceProofAssistant();
        cmdBtns.forEach(btn => {
            btn.addEventListener("click", () => {
                if (this.cmd.cmdBuffer.length) return;
                this.cmd.cmdBuffer.push(btn.innerText.replace(/.+\((.+)\)/g, "$1"));
                this.cmd.execCmdBuffer();
            });
        });
        document.querySelectorAll("label.before-list-wrapper").forEach(v => {
            const div = v.nextElementSibling as HTMLDivElement;
            v.addEventListener("click", () => {
                div.classList.toggle("hide-animation");
            });
        })
        const simplSysFn = document.getElementById("simpl-sysfn") as HTMLInputElement;
        const italicItemBox = document.getElementById("italic-item") as HTMLInputElement;
        const onchangeOmitNF = () => {
            this.omitNfFn = document.getElementById("wrap-simpl-sysfn").classList.contains("hide") ? false : simplSysFn.checked;
            this.italicItem = document.getElementById("wrap-italic-item").classList.contains("hide") ? false : italicItemBox.checked;
            this.updateSysFnList();
            this.updateMetaRuleList(true);
            this.updateDeductionList();
            this.updatePropositionList(true);
        };
        this.onchangeOmitNF = onchangeOmitNF;
        simplSysFn.addEventListener("change", onchangeOmitNF);
        italicItemBox.addEventListener("change", onchangeOmitNF);
        document.querySelectorAll(".footer .right button").forEach((btn: HTMLElement) => {
            btn.addEventListener("click", () => {
                if (btn.innerText === "OK") {
                    this.cmd.actionInputKeydown({ key: "Enter" });
                } else if (btn.innerText === "Esc") {
                    this.cmd.actionInputKeydown({ key: "Escape" });
                }
            });
        });
        this.draggerD.onExecute = (src, dst) => {
            const mv = (src: string, dst: string) => {
                const srcPos = this.deductions.indexOf(src);
                let dstPos = this.deductions.indexOf(dst);
                if (dstPos > srcPos) dstPos--;
                if (srcPos === -1) return false;
                if (dstPos === -1 && dst !== " ") return false;
                const moved = this.deductions.splice(this.deductions.indexOf(src), 1)[0];
                if (dstPos === -1) this.deductions.push(moved);
                else this.deductions.splice(dstPos, 0, moved);
                return true;
            }

            const idx = this.deductions.indexOf(dst);
            const prevDst = idx === -1 ? this.deductions[this.deductions.length - 1] : (this.deductions[idx - 1] ?? "");
            const table = this.scanDeductionFolderScope([src, prevDst]);
            table[src] ??= [];
            table[prevDst] ??= [];
            let moved = 1;
            const movedSrcs = [src];
            let src_uuid = null;
            if (src.startsWith("< f >")) {
                const [_, srcCount, srcuuid] = src.split("::");
                src_uuid = srcuuid;
                moved += Number(srcCount);
                if (table[prevDst].find(e => e[0] === srcuuid)) {
                    return; // cannot move into itself
                }
                const srcidx = this.deductions.indexOf(src);
                const end = srcidx + 1 + Number(srcCount);
                for (let i = srcidx + 1; i < end; i++) {
                    movedSrcs.push(this.deductions[i]);
                }
            }
            for (const [fuuid] of table[src]) {
                if (src_uuid !== fuuid) {
                    this.setDeductionFolderCount(fuuid, (fcount) => fcount - moved);
                }
            }
            for (const [fuuid] of table[prevDst]) {
                const dir = this.deductions.find(d => d.startsWith("< f >") && d.split("::")[2] === fuuid);
                if (dir.endsWith("+")) break;
                this.setDeductionFolderCount(fuuid, (fcount) => fcount + moved);
            }
            if (dst.startsWith("< f >")) {
                const uuid = dst.split("::")[2];
                dst = this.deductions.find(d => d.startsWith("< f >") && d.split("::")[2] === uuid);
            }
            if (src !== dst) for (const s of movedSrcs) mv(s, dst);
            this.updateDeductionList();
        }
        this.draggerM.onExecute = (src, dst) => {
            src = src.slice(1);
            dst = dst.slice(1);
            const srcPos = this.metarules.indexOf(src);
            let dstPos = this.metarules.indexOf(dst);
            if (dstPos > srcPos) dstPos--;
            if (srcPos === -1) return;
            if (dstPos === -1 && dst !== " ") return;
            const moved = this.metarules.splice(this.metarules.indexOf(src), 1)[0];
            if (dstPos === -1) this.metarules.push(moved);
            else this.metarules.splice(dstPos, 0, moved);
            this.updateMetaRuleList(true);
        }
        this.draggerP.queryAllowDrag = () => this.cmd.cmdBuffer.length === 0;
        this.draggerP.onExecute = (src, dst) => {
            const pl = this.formalSystem.propositions.length;
            try {
                const s = Number(src.slice(1));
                const d = dst === " " ? -1 : Number(dst.slice(1));
                this.formalSystem.moveProposition(s, d);
                this.updatePropositionList(true);
            } catch (e) {
                if (pl !== this.formalSystem.propositions.length) {
                    this.updatePropositionList(true);
                }
                this.hintText.innerText = e;
            }
        }
        this.initInferencePages();
        if (creative) {
            this.initCreative();
        }
        this.updateMetaRuleList();
        this.updateDeductionList();
        this.updateSysFnList();
        onchangeOmitNF();
    }
    /** Persist the active page before changing pages or leaving the UI state. */
    private saveActiveInferencePage() {
        const page = this.pageStore.active;
        if (this.inferenceProofAssistant && this.inferenceProofPageId === page.id) {
            this.persistInferenceProofDraft();
        }
        // `entr` temporarily swaps the engine list while retaining the
        // persistent page in cmdBuffer[2].  Never persist that temporary
        // expansion as the page's actual theorem list.
        const persistentProps = this.cmd.cmdBuffer[0] === "entr" && Array.isArray(this.cmd.cmdBuffer[2])
            ? this.cmd.cmdBuffer[2]
            : this.formalSystem.propositions;
        page.propositions = persistentProps as any;
        const previousState = (page.command.state && typeof page.command.state === "object")
            ? page.command.state as Record<string, unknown>
            : {};
        this.pageStore.setCommandSnapshot({
            input: this.actionInput.value,
            buffer: this.cmd.cmdBuffer.slice() as any,
            state: {
                ...previousState,
                escClear: this.cmd.escClear,
                lastDeduction: this.cmd.lastDeduction,
                hint: this.hintText.innerHTML
            }
        });
    }
    private restoreInferencePage(page: InferencePage<any>) {
        this.formalSystem.propositions = page.propositions as any;
        this.cmd.cmdBuffer = page.command.buffer.slice() as any[];
        this.actionInput.value = page.command.input;
        const state = page.command.state as { escClear?: boolean; lastDeduction?: string; hint?: string } | undefined;
        if (state) {
            if (typeof state.escClear === "boolean") this.cmd.escClear = state.escClear;
            if (state.lastDeduction !== undefined) this.cmd.lastDeduction = state.lastDeduction;
            if (state.hint !== undefined) this.hintText.innerHTML = state.hint;
        }
        this.cmd.pListMasked = false;
        this.renderInferencePages();
        this.updatePropositionList(true);
        this.updateDeductionList();
        this.restoreInferenceProofDraft(page);
    }
    /** Store the active assistant draft in the selected page's command state. */
    private persistInferenceProofDraft() {
        if (!this.inferenceProofAssistant || !this.inferenceProofPageId) return;
        const page = this.pageStore.page(this.inferenceProofPageId);
        if (!page) return;
        const state = page.command.state && typeof page.command.state === "object"
            ? page.command.state as Record<string, unknown>
            : {};
        const snapshot = this.inferenceProofAssistant.snapshot();
        page.command.state = {
            ...state,
            inferenceProof: {
                theorem: snapshot.theorem,
                history: snapshot.history,
                ...(this.inferenceProofTextMode ? {
                    script: (document.getElementById("fs-proof-script") as HTMLTextAreaElement | null)?.value ?? this.inferenceProofScript
                } : {}),
                textMode: this.inferenceProofTextMode
            } satisfies PersistedInferenceProofDraft
        };
    }
    /** Remove a persisted draft after an explicit close or successful qed. */
    private clearPersistedInferenceProofDraft(pageId = this.inferenceProofPageId) {
        if (!pageId) return;
        const page = this.pageStore.page(pageId);
        if (!page) return;
        const state = page.command.state;
        if (!state || typeof state !== "object") return;
        const next = { ...(state as Record<string, unknown>) };
        delete next.inferenceProof;
        page.command.state = next;
    }
    /** Suspend the UI session while retaining a page-local proof draft. */
    private suspendInferenceProofAssistant() {
        if (!this.inferenceProofAssistant) return;
        this.persistInferenceProofDraft();
        this.resetInferenceProofUi();
    }
    /** Restore a page-local assistant draft after switching or loading. */
    private restoreInferenceProofDraft(page: InferencePage<any>) {
        const state = page.command.state;
        const draft = state && typeof state === "object"
            ? (state as Record<string, unknown>).inferenceProof as Partial<PersistedInferenceProofDraft> | undefined
            : undefined;
        if (!draft || !draft.theorem || !Array.isArray(draft.history)) return;
        try {
            const assistant = new InferenceProofAssistant(this.formalSystem, draft.theorem, {
                pageId: page.id,
                history: draft.history,
                ruleNames: this.deductions,
                fastMetaRules: this.formalSystem.fastmetarules,
                allowMcpt: this.metarules.includes("cpt")
            });
            this.inferenceProofAssistant = assistant;
            this.inferenceProofPageId = page.id;
            this.inferenceProofSnapshot = assistant.snapshot();
            this.inferenceProofTextMode = draft.textMode === true;
            this.inferenceProofScript = typeof draft.script === "string"
                ? draft.script.split(/\r?\n/).map(migrateInferenceProofCommand).join("\n")
                : migrateInferenceProofHistory(draft.history).join("\n");
            this.inferenceProofScriptDirty = typeof draft.script === "string";
            this.renderInferenceProofSnapshot(this.inferenceProofSnapshot);
        } catch (error) {
            // A stale draft must not prevent the page itself from loading.
            this.clearPersistedInferenceProofDraft(page.id);
            this.setInferenceProofError(error);
        }
    }
    /** Replace page state after loading a save, keeping the active engine array in sync. */
    loadInferencePages(serialized?: SerializedInferencePages<any>, propositions?: any[]) {
        if (this.inferenceProofAssistant) this.closeInferenceProofAssistant();
        if (serialized) this.formalSystem.restoreInferencePages(serialized as any);
        else {
            this.formalSystem.restoreInferencePages({
                activeId: "page-1",
                pages: [{ id: "page-1", name: "主表", propositions: propositions ?? [], command: { input: "", buffer: [] } }]
            } as any);
        }
        this.formalSystem.propositions = this.pageStore.active.propositions as any;
        this.cmd.cmdBuffer = this.pageStore.active.command.buffer.slice() as any[];
        this.actionInput.value = this.pageStore.active.command.input;
        const state = this.pageStore.active.command.state as { escClear?: boolean; lastDeduction?: string; hint?: string } | undefined;
        if (state?.escClear !== undefined) this.cmd.escClear = state.escClear;
        if (state?.lastDeduction !== undefined) this.cmd.lastDeduction = state.lastDeduction;
        if (state?.hint !== undefined) this.hintText.innerHTML = state.hint;
        this.cmd.pListMasked = false;
        this.renderInferencePages();
        this.restoreInferenceProofDraft(this.pageStore.active);
    }
    private initInferencePages() {
        if (!this.pageTabs) return;
        this.renderInferencePages();
    }
    createInferencePage(name: string) {
        const page = this.pageStore.create(name.trim());
        this.renderInferencePages();
        return page;
    }
    private createInferencePageFromPrompt() {
        const name = window.prompt(TR("请输入新推理表名称"), "");
        if (name === null) return;
        try {
            this.createInferencePage(name);
            this.onStateChange();
        } catch (e) {
            this.hintText.innerText = String(e);
        }
    }
    activateInferencePage(id: string) {
        if (id === this.pageStore.activeId) return;
        const page = this.pageStore.page(id);
        if (!page) {
            this.hintText.innerText = TR("推理表不存在：") + id;
            return;
        }
        const previousPageId = this.pageStore.activeId;
        const previousAssistant = this.inferenceProofAssistant;
        const previousSnapshot = this.inferenceProofSnapshot;
        const previousProofPageId = this.inferenceProofPageId;
        try {
            // Proof drafts are page-local. Suspend the active draft into the
            // page command state before switching so it can be restored later.
            this.suspendInferenceProofAssistant();
            this.saveActiveInferencePage();
            const activated = this.pageStore.activate(page.id);
            this.restoreInferencePage(activated);
            this.onStateChange();
        } catch (e) {
            // Restore the prior page and live assistant if rendering or draft
            // restoration failed after the page switch began.
            try {
                const previousPage = this.pageStore.page(previousPageId);
                if (previousPage) {
                    this.pageStore.activate(previousPage.id);
                    this.formalSystem.propositions = previousPage.propositions as any;
                    this.cmd.cmdBuffer = previousPage.command.buffer.slice() as any[];
                    this.actionInput.value = previousPage.command.input;
                    this.cmd.pListMasked = false;
                    this.renderInferencePages();
                    this.updatePropositionList(true);
                    this.updateDeductionList();
                }
                this.inferenceProofAssistant = previousAssistant;
                this.inferenceProofSnapshot = previousSnapshot;
                this.inferenceProofPageId = previousProofPageId;
                if (previousSnapshot) this.renderInferenceProofSnapshot(previousSnapshot);
                else if (!previousAssistant) this.resetInferenceProofUi();
            } catch {
                // Keep the original page-switch diagnostic below.
            }
            this.hintText.innerText = String(e);
        }
    }
    deleteInferencePage(id: string) {
        const page = this.pageStore.page(id);
        if (!page || this.pageStore.size <= 1) {
            this.hintText.innerText = TR("至少需要保留一个推理表");
            return;
        }
        if (!window.confirm(TR("确定删除推理表<") + page.name + TR(">吗？"))) return;
        try {
            if (id === this.inferenceProofPageId) this.suspendInferenceProofAssistant();
            this.saveActiveInferencePage();
            const wasActive = page.id === this.pageStore.activeId;
            this.pageStore.delete(id);
            if (wasActive) this.restoreInferencePage(this.pageStore.active);
            else this.renderInferencePages();
            // Command-driven deletion persists after the command buffer is
            // cleared by FSCmd; direct tab deletion persists immediately.
            if (this.cmd.cmdBuffer[0] !== "delpage") this.onStateChange();
        } catch (e) {
            this.hintText.innerText = String(e);
        }
    }
    renderInferencePages() {
        const tabs = this.pageTabs;
        if (!tabs) return;
        tabs.replaceChildren();
        for (const page of this.pageStore.pages) {
            const tab = document.createElement("div");
            tab.className = "inference-page-tab" + (page.id === this.pageStore.activeId ? " active" : "");
            tab.dataset.pageId = page.id;
            tab.draggable = true;
            const label = document.createElement("button");
            label.type = "button";
            label.className = "inference-page-label";
            label.textContent = page.name;
            label.title = TR("切换推理表") + `：${page.name}`;
            label.addEventListener("click", () => this.activateInferencePage(page.id));
            tab.appendChild(label);
            const close = document.createElement("button");
            close.type = "button";
            close.className = "inference-page-close";
            close.textContent = "×";
            close.title = TR("删除推理表");
            close.addEventListener("click", e => { e.stopPropagation(); this.deleteInferencePage(page.id); this.onStateChange(); });
            tab.appendChild(close);
            tab.addEventListener("dragstart", e => {
                e.dataTransfer?.setData("text/inference-page", page.id);
                if (e.dataTransfer) e.dataTransfer.effectAllowed = "move";
                tab.classList.add("dragging");
            });
            tab.addEventListener("dragend", () => tab.classList.remove("dragging"));
            tab.addEventListener("dragover", e => { e.preventDefault(); tab.classList.add("drag-over"); });
            tab.addEventListener("dragleave", () => tab.classList.remove("drag-over"));
            tab.addEventListener("drop", e => {
                e.preventDefault();
                tab.classList.remove("drag-over");
                const source = e.dataTransfer?.getData("text/inference-page");
                if (!source || source === page.id) return;
                try {
                    this.saveActiveInferencePage();
                    this.pageStore.reorder(source, page.id);
                    this.renderInferencePages();
                    this.onStateChange();
                } catch (err) { this.hintText.innerText = String(err); }
            });
            tabs.appendChild(tab);
        }
        const add = document.createElement("button");
        add.type = "button";
        add.className = "inference-page-add";
        add.textContent = "+";
        add.title = TR("新建推理表");
        add.addEventListener("click", () => this.createInferencePageFromPrompt());
        tabs.appendChild(add);
        // Dropping on the empty strip or the plus button appends the page.
        tabs.ondragover = e => {
            if ((e.target as HTMLElement).closest(".inference-page-tab")) return;
            e.preventDefault();
        };
        tabs.ondrop = e => {
            if ((e.target as HTMLElement).closest(".inference-page-tab")) return;
            e.preventDefault();
            const source = e.dataTransfer?.getData("text/inference-page");
            if (!source) return;
            try {
                this.saveActiveInferencePage();
                this.pageStore.reorder(source, null);
                this.renderInferencePages();
                this.onStateChange();
            } catch (err) { this.hintText.innerText = String(err); }
        };
    }
    reload() {
        this.formalSystem.fastmetarules = "";
        this.enableMIFFT_RP = false;
    }
    initCreative() {
        this.metarules = Object.keys(this.formalSystem.metaRules);
        this.formalSystem.fastmetarules = "cvuqe><:#zZQR";
        document.getElementById("metarule-subpanel").classList.remove("hide");
        document.getElementById("macro-btns").classList.remove("hide");
        this.unlockedHyp = true;
        this.unlockedRename = true;
        this.unlockedFolder = true;
        this.unlockedSysRulePanel = true;
        this.unlockedMacro = true;
        this.enableMIFFT_RP = true;
        document.getElementById("hyp-btn").classList.remove("hide");
        document.getElementById("ach").classList.add("hide");
        document.getElementById("wrap-simpl-sysfn").classList.remove("hide");
        document.getElementById("wrap-italic-item").classList.remove("hide");
        document.getElementById("stat").classList.add("hide");
        document.getElementById("creer").classList.remove("hide");
        document.getElementById("dir-btn").classList.remove("hide");
        document.getElementById("rename-btn").classList.remove("hide");
    }
    prettyPrint(s: string) {
        return s.replace(/>=/g, "≥").replace(/<=/g, "≤").replace(/<>/g, "↔").replace(/>/g, "→").replace(/</g, "⊂").replace(/@/g, "∈")
            .replace(/U/g, "∪").replace(/I/g, "∩").replace(/\*/g, "×").replace(/X/g, "×").replace(/\//g, "÷").replace(/-/g, "−")
            .replace(/\|/g, "∨").replace(/÷∨/g, "|").replace(/&/g, "∧").replace(/~/g, "¬").replace(/V/g, "∀").replace(/E/g, "∃").replace(/omega/g, "ω");
    }
    addSpan(parentSpan: HTMLSpanElement, text: string, parseHTML?: boolean) {
        const span = document.createElement("span");
        if (parseHTML) span.innerHTML = text; else span.innerText = text;
        parentSpan.appendChild(span);
        return span;
    }
    ast2HTML(idx: string, ast: AST, isItem: boolean, scopes: AST[] = []) {
        const varnode = document.createElement("span");
        const astStr = this.cmd.astparser.stringify(ast);
        varnode.setAttribute("ast-string", astStr);
        if (ast.type === "rule") {
            this.addSpan(varnode, '"');
            varnode.appendChild(this.tree2HTML(this.formalSystem.getDeductionTokens(ast.name)));
            this.addSpan(varnode, '"');
        } else if (ast.type === "meta") {
            this.addSpan(varnode, "(");
            let firstTerm = true;
            for (const n of ast.nodes[0].nodes) {
                if (firstTerm) { firstTerm = false; } else {
                    this.addSpan(varnode, ", ");
                }
                varnode.appendChild(this.ast2HTML(idx, n, false, scopes));
            }
            if (ast.name === "⊢M") {
                this.addSpan(varnode, ` ⊢<sub>M</sub> `, true);
            } else {
                this.addSpan(varnode, ` ${ast.name} `);
            }
            firstTerm = true;
            for (const n of ast.nodes[1].nodes) {
                if (firstTerm) { firstTerm = false; } else {
                    this.addSpan(varnode, ", ");
                }
                varnode.appendChild(this.ast2HTML(idx, n, false, scopes));
            }

            this.addSpan(varnode, ")");

        } else if (ast.type === "fn") {
            if (ast.name === "{") {
                this.addSpan(varnode, "{");
                let firstTerm = true;
                for (const n of ast.nodes) {
                    if (firstTerm) { firstTerm = false; } else {
                        this.addSpan(varnode, ", ");
                    }
                    varnode.appendChild(this.ast2HTML(idx, n, true, scopes));
                }
                this.addSpan(varnode, "}");
            } else {
                // todo: add show/hide #nf/vnf
                const omitNfFn = (ast.name.match(/^#(v*)nf$/) || ast.name.match(/^#rp$/)) && this.omitNfFn;
                if (!omitNfFn) {
                    if (ast.name !== "(") {
                        const fnName = this.addSpan(varnode, ast.name);
                        if (ast.name.startsWith("#")) fnName.classList.add("sysfn");
                        if (this.formalSystem.fns.has(ast.name)) fnName.classList.add("fn");
                        if (this.formalSystem.verbs.has(ast.name)) fnName.classList.add("verb");
                    }
                    this.addSpan(varnode, "(");
                }
                const fonts = []; // 0 for mormal, 1 for sup, -1 for sub
                for (const [nidx, n] of ast.nodes.entries()) {
                    let subIsItem = ast.name.match(/^##match/) ? nidx === 3 : ast.name.match(/^#((v*)nf|#?rp)/) ? nidx === 0 ? isItem : true : true;
                    let font = 0;
                    const node = this.ast2HTML(idx, n, subIsItem, scopes);
                    if (ast.name.match(/^#(v*)nf/)) {
                        font = (nidx > ast.name.length - 3) ? -1 : 1;
                    }
                    if (ast.name.match(/^#(#match)?rp/)) {
                        if (nidx === 0) varnode.classList.add("rp");
                        font = nidx === 2 ? -1 : nidx === 1 ? 1 : 0;
                    }
                    if (!nidx) {
                        font = 0;
                    } else {
                        if (ast.name.match(/^#(v*)nf/)) node.setAttribute("ast-string", astStr);
                    }
                    fonts.push(font);
                    const noComma = (nidx >= 1);
                    if (nidx && !font && !fonts[nidx - 1]) this.addSpan(varnode, ", ");
                    if (omitNfFn && !nidx) varnode.classList.add("omit-nf");
                    if (font) {
                        const wrappedNode = document.createElement(font === 1 ? "sup" : "sub");
                        wrappedNode.classList.add("omit-nf");
                        varnode.appendChild(wrappedNode);
                        if (ast.name.match(/^#(v*)nf/) && nidx > ast.name.length - 3) wrappedNode.classList.add("nf");
                        if (ast.name.match(/^#(v*)nf/) && nidx === 1 && nidx <= ast.name.length - 3) {
                            wrappedNode.prepend(this.addSpan(wrappedNode, "∀"));
                        }
                        if (ast.name.match(/^#(#match)?rp/)) {
                            if (nidx === 2) {
                                const span = document.createElement("span");
                                node.before(span);
                                span.innerText = "↘";
                                wrappedNode.before(span);
                            }
                        }
                        if (nidx && font === fonts[nidx - 1])
                            wrappedNode.appendChild(this.addSpan(wrappedNode, ","));
                        wrappedNode.appendChild(node);
                    } else {
                        varnode.appendChild(node);
                    }
                    if (ast.name.match(/^#(#match)?rp/)) {
                        if (nidx === 3) {
                            const span = document.createElement("span");
                            node.before(span);
                            span.innerText = ",";
                            node.classList.add("rp-nth");
                        }
                    }
                }
                if (!omitNfFn) this.addSpan(varnode, ")");
            }
        } else if (ast.type === "replvar") {
            const printForm = {
                "omega": "ω",
                "N": "ℕ",
                "Z": "ℤ",
                "Q": "ℚ",
                "R": "ℝ",
            }
            const el = this.addSpan(varnode, printForm[ast.name] ?? ast.name);
            if (isItem && this.italicItem) el.classList.add("item");
            const scopeStack = scopes.slice(0);
            if (this.formalSystem.assert.isConst(ast.name)) {
                el.classList.add("constant");
            } else if (ast.name.replace(/^\.\.\./, "").match(this.formalSystem.deductionReplNameRule)) {
                el.classList.add("replvar");
            } else {
                el.classList.add("freeVar");
            }
            if (scopeStack[0]?.type === "quantvar") {
                // quantvar is only aimed for mark css style
                if (!el.classList.contains("replvar")) {
                    el.classList.remove("freeVar");
                    el.classList.add("boundedVar");
                }
                scopeStack.pop();
            }
            do {
                if (scopeStack[0] && (scopeStack[0]?.nodes[0]?.name === ast.name) || (scopeStack[0]?.nodes[0]?.nodes?.[0]?.name === ast.name)) {
                    varnode.setAttribute("ast-scope", this.cmd.astparser.stringify(scopeStack[0]));
                    if (!el.classList.contains("replvar")) {
                        el.classList.remove("freeVar");
                        el.classList.add("boundedVar");
                    }
                    break;
                }
            } while (scopeStack.shift());
        } else {
            switch (ast.name) {
                case "~": case "!":
                    this.addSpan(varnode, this.prettyPrint(ast.name));
                    varnode.appendChild(this.ast2HTML(idx, ast.nodes[0], ast.name === "!", scopes));
                    break;
                case "{|":
                case "|}":
                case "V": case "E": case "E!":
                    const outterLayers: HTMLSpanElement[] = [];
                    outterLayers.push(this.addSpan(varnode, (ast.name === "{|" || ast.name === "|}") ? "{" : ("(" + this.prettyPrint(ast.name))));
                    const varast = this.ast2HTML(idx, ast.nodes[0], true, [{ type: "quantvar", name: "quantvar" }]);
                    varast.classList.add("boundedVar");
                    if (ast.name === "{|") {
                        outterLayers.push(varnode.appendChild(varast));
                        outterLayers.push(this.addSpan(varnode, this.prettyPrint("@")));
                        varnode.appendChild(this.ast2HTML(idx, ast.nodes[1], true, scopes));
                        outterLayers.push(this.addSpan(varnode, "|"));
                        varnode.appendChild(this.ast2HTML(idx, ast.nodes[2], false, [ast, ...scopes]));
                        outterLayers.push(this.addSpan(varnode, "}"));

                    } else if (ast.name === "|}") {
                        varnode.appendChild(this.ast2HTML(idx, ast.nodes[2], true, [ast, ...scopes]));
                        outterLayers.push(this.addSpan(varnode, "|"));
                        outterLayers.push(varnode.appendChild(varast));
                        outterLayers.push(this.addSpan(varnode, this.prettyPrint("@")));
                        varnode.appendChild(this.ast2HTML(idx, ast.nodes[1], true, scopes));
                        outterLayers.push(this.addSpan(varnode, "}"));
                    } else {
                        outterLayers.push(varnode.appendChild(varast));
                        outterLayers.push(this.addSpan(varnode, ":"));
                        varnode.appendChild(this.ast2HTML(idx, ast.nodes[1], false, [ast, ...scopes]));
                        outterLayers.push(this.addSpan(varnode, ")"));
                    }

                    // hightlight constrained vars

                    const constrainedVars = Array.from(varnode.querySelectorAll("span")).filter(
                        node => (node as HTMLSpanElement).getAttribute("ast-scope") === astStr
                    ) as HTMLSpanElement[];
                    for (const node of constrainedVars) {
                        node.addEventListener('mouseover', ev => {
                            for (const node of outterLayers) {
                                node.classList.add("highlighted");
                            }
                        });
                        node.addEventListener('mouseout', ev => {
                            for (const node of outterLayers) {
                                node.classList.remove("highlighted");
                            }
                        });
                    }
                    outterLayers[1].addEventListener('mouseover', ev => {
                        for (const node of constrainedVars) {
                            node.classList.add("highlighted");
                        }
                    });
                    outterLayers[1].addEventListener('mouseout', ev => {
                        for (const node of constrainedVars) {
                            node.classList.remove("highlighted");
                        }
                    });
                    break;
                default:
                    this.addSpan(varnode, "(");
                    const subIsItem = "-@<=+*UIX/\\".includes(ast.name) || ast.name === "/|" || ast.name === ">=";
                    varnode.appendChild(this.ast2HTML(idx, ast.nodes[0], subIsItem, scopes));
                    this.addSpan(varnode, ast.name.startsWith("$$") ? ` ${ast.name} ` : this.prettyPrint(ast.name));
                    varnode.appendChild(this.ast2HTML(idx, ast.nodes[1], subIsItem, scopes));
                    this.addSpan(varnode, ")");
            }
        }

        // clicks and hovers in this layer
        const spans = Array.from(varnode.childNodes).filter(
            node => ((node as HTMLSpanElement).getAttribute && !(node as HTMLSpanElement).getAttribute("ast-string"))
        ) as HTMLSpanElement[];
        for (const node of spans) {
            node.addEventListener('mouseover', ev => {
                for (const node of spans) {
                    node.classList.add("highlighted");
                }
            });
            node.addEventListener('mouseout', ev => {
                for (const node of spans) {
                    node.classList.remove("highlighted");
                }
            });
            node.addEventListener('click', ev => {
                ev.stopPropagation();
                this.cmd.onClickSubAst(idx, varnode.getAttribute("ast-string"));
            });
        }
        return varnode;
    }
    private _convert(d: Deduction) {
        let str = this.cmd.astparser.stringifyTight(d.value);
        let steps = d.steps?.map(step => [step.deductionIdx, step.conditionIdxs, step.replaceValues.map((v, i) => this.cmd.astparser.stringifyTight(
            v, this.formalSystem.assert.expand(v, d.replaceTypes[i])
        ))]);
        if (d.tempvars?.size) {
            console.log(JSON.stringify([str, "内置宏", steps, Array.from(d.tempvars)]));
            return [str, JSON.stringify(steps), Array.from(d.tempvars)];
        }
        console.log(JSON.stringify([str, "内置宏", steps]));
        return [str, JSON.stringify(steps)];
    }
    private updateGuiList<T extends { value: AST }>(
        prefix: string, logicArray: T[] | { [name: string]: T }, list: HTMLElement,
        filter: (term: T, idx: string) => boolean,
        setInfo: (term: T, itInfo: HTMLElement[], it: HTMLElement, label: string) => void,
        refresh?: boolean, customIdx?: string[]
    ) {
        this.onStateChange();
        if (refresh) {
            while (list.lastChild) {
                list.removeChild(list.lastChild);
            }
            list.setAttribute("total", "0");
        }
        let listLength = Number(list.getAttribute("total")) || 0;
        const values = Object.values(logicArray);
        const keys = Object.keys(logicArray);
        const targetLength = values.length;
        list.setAttribute("total", String(targetLength));
        for (; listLength > targetLength; listLength--) {
            const p = values[listLength];
            if (!filter(p, keys[listLength])) continue;
            for (let i = 0; i < 8; i++) list.removeChild(list.lastChild);
        }
        for (; listLength < targetLength; listLength++) {
            const p = values[listLength];
            const pname = customIdx ? customIdx[listLength] : prefix + listLength;
            if (!filter(p, keys[listLength])) continue;

            const itIdx = document.createElement("div");
            list.appendChild(itIdx);
            itIdx.classList.add("idx");
            itIdx.innerText = pname;

            const itVal = document.createElement("div");
            list.appendChild(itVal);
            itVal.classList.add("val");
            itVal.appendChild(this.ast2HTML(pname, p.value, false));

            const infoArr = [];
            for (let i = 0; i < 6; i++) {
                const itInfo = document.createElement("div");
                list.appendChild(itInfo);
                itInfo.className = "info";
                infoArr.push(itInfo);
            }
            setInfo(p, infoArr, itVal, pname);

            itVal.addEventListener("click", () => {
                const inserted = this.cmd.astparser.stringify(p.value);
                this.cmd.onClickSubAst(pname, inserted);
            });
        }
        list.scroll({ top: list.scrollHeight });
    }
    showWaitingAst(ast: AST) {
        const target = document.getElementById("copygateD");
        if (!target) return;
        target.replaceChildren();
        target.appendChild(this.ast2HTML("-", ast, false));
        const begin = document.createElement("button");
        begin.type = "button";
        begin.className = "inhabitat-modify fs-proof-gate-begin";
        begin.textContent = "+";
        begin.title = TR("用推理层证明助手证明此命题");
        begin.addEventListener("click", () => this.startInferenceProofAssistant(ast));
        target.appendChild(begin);
        const input = document.getElementById("fs-proof-target") as HTMLInputElement | null;
        if (input) input.value = this.cmd.astparser.stringifyTight(ast);
    }
    /** Wire the deduction-layer assistant without sharing TT tactic controls. */
    private initInferenceProofAssistant() {
        const begin = document.getElementById("fs-proof-begin");
        const target = document.getElementById("fs-proof-target") as HTMLInputElement | null;
        const input = document.getElementById("fs-proof-input") as HTMLTextAreaElement | null;
        const apply = document.getElementById("fs-proof-apply");
        const undo = document.getElementById("fs-proof-undo");
        const close = document.getElementById("fs-proof-close");
        const qed = document.getElementById("fs-proof-qed");
        if (!begin || !target || !input || !apply || !undo || !close || !qed) return;

        begin.addEventListener("click", () => this.startInferenceProofFromInput());
        target.addEventListener("keydown", event => {
            if (event.key !== "Enter") return;
            event.preventDefault();
            this.startInferenceProofFromInput();
        });
        input.addEventListener("keydown", event => {
            if (event.key === "Enter" && !event.shiftKey) {
                event.preventDefault();
                this.applyInferenceProofCommand();
            } else if (event.key === "Escape") {
                event.preventDefault();
                input.value = "";
            }
        });
        apply.addEventListener("click", () => this.applyInferenceProofCommand());
        undo.addEventListener("click", () => this.undoInferenceProof());
        close.addEventListener("click", () => this.closeInferenceProofAssistant());
        qed.addEventListener("click", () => {
            const name = (document.getElementById("fs-proof-name") as HTMLInputElement | null)?.value.trim();
            this.finishInferenceProof(name || undefined);
        });
        document.getElementById("fs-proof-text-toggle")?.addEventListener("click", () => {
            this.toggleInferenceProofTextMode();
        });
        const script = document.getElementById("fs-proof-script") as HTMLTextAreaElement | null;
        if (script) this.inferenceProofScriptEditor = new ProofScriptEditor(script);
        script?.addEventListener("input", () => {
            this.inferenceProofScript = script.value;
            this.inferenceProofScriptDirty = true;
            this.persistInferenceProofDraft();
            this.scheduleInferenceProofTextReplay();
        });
        const scheduleInferenceCaretReplay = () => this.scheduleInferenceProofTextReplay();
        script?.addEventListener("selectionchange", scheduleInferenceCaretReplay);
        script?.addEventListener("click", scheduleInferenceCaretReplay);
        script?.addEventListener("keyup", scheduleInferenceCaretReplay);
        script?.addEventListener("keydown", event => {
            if (event.key === "Enter" && event.ctrlKey) {
                event.preventDefault();
                this.replayInferenceProofText(true, true);
            }
        });
        document.getElementById("fs-proof-script-run-cursor")?.addEventListener("click", () => {
            this.replayInferenceProofText(true, true);
        });
        document.getElementById("fs-proof-script-run")?.addEventListener("click", () => {
            this.replayInferenceProofText(true, false);
        });
    }
    private renderInferenceProofRecommendations() {
        const container = document.getElementById("fs-proof-commands");
        if (!container) return;
        container.replaceChildren();
        if (!this.inferenceProofAssistant) return;
        const commands = this.inferenceProofAssistant.recommendations({
            ruleNames: this.deductions,
            canTauto: this.metarules.includes("cpt")
        });
        for (const command of commands) {
            const button = document.createElement("button");
            button.type = "button";
            button.className = "fs-proof-command";
            button.textContent = command;
            button.title = TR("执行推荐策略") + `：${command}`;
            button.addEventListener("click", () => {
                const input = document.getElementById("fs-proof-input") as HTMLTextAreaElement | null;
                if (!input) return;
                input.value = command;
                input.focus();
                const placeholder = command.indexOf("??");
                if (placeholder >= 0) {
                    input.selectionStart = placeholder;
                    input.selectionEnd = placeholder + 2;
                    return;
                }
                this.applyInferenceProofCommand();
            });
            container.appendChild(button);
        }
    }
    private renderInferenceProofTextRecommendations() {
        const container = document.getElementById("fs-proof-script-recommendations");
        if (!container) return;
        container.replaceChildren();
        if (!this.inferenceProofAssistant) return;
        const commands = this.inferenceProofAssistant.recommendations({
            ruleNames: this.deductions,
            canTauto: this.metarules.includes("cpt")
        });
        if (!commands.length) return;
        container.appendChild(document.createTextNode(TR("推荐：")));
        commands.forEach((command, index) => {
            if (index) container.appendChild(document.createTextNode("  |  "));
            const code = document.createElement("code");
            code.textContent = command;
            container.appendChild(code);
        });
    }
    /** Start a page-local deduction proof.  The page itself is not mutated. */
    startInferenceProofAssistant(target: AST | string, pageId?: string): InferenceProofSnapshot | null {
        const page = this.pageStore.page(pageId ?? this.pageStore.activeId);
        if (!page) {
            this.setInferenceProofError(TR("推理表不存在"));
            return null;
        }
        let assistant: InferenceProofAssistant;
        let snapshot: InferenceProofSnapshot;
        try {
            // Construct the replacement session first.  A malformed target
            // must leave the currently edited proof untouched.
            assistant = new InferenceProofAssistant(this.formalSystem, target, {
                pageId: page.id,
                ruleNames: this.deductions,
                fastMetaRules: this.formalSystem.fastmetarules,
                allowMcpt: this.metarules.includes("cpt")
            });
            snapshot = assistant.snapshot();
        } catch (error) {
            this.setInferenceProofError(error);
            return null;
        }
        try {
            const previousPageId = this.inferenceProofPageId;
            if (previousPageId) this.clearPersistedInferenceProofDraft(previousPageId);
            this.resetInferenceProofUi();
            this.inferenceProofAssistant = assistant;
            this.inferenceProofPageId = page.id;
            this.inferenceProofSnapshot = snapshot;
            const targetInput = document.getElementById("fs-proof-target") as HTMLInputElement | null;
            if (targetInput) targetInput.value = this.cmd.astparser.stringifyTight(snapshot.theorem);
            this.renderInferenceProofSnapshot(snapshot);
            this.persistInferenceProofDraft();
            this.onStateChange();
            return this.inferenceProofSnapshot;
        } catch (error) {
            this.setInferenceProofError(error);
            return null;
        }
    }
    /** Start from the assistant target field, falling back to the command input. */
    startInferenceProofFromInput(): InferenceProofSnapshot | null {
        const targetInput = document.getElementById("fs-proof-target") as HTMLInputElement | null;
        const target = targetInput?.value.trim() || this.actionInput.value.trim();
        if (!target) {
            this.setInferenceProofError(TR("请输入待证命题"));
            return null;
        }
        return this.startInferenceProofAssistant(target);
    }
    private renderInferenceProofSnapshot(snapshot: InferenceProofSnapshot) {
        if (this.inferenceProofTextMode) {
            this.renderInferenceProofTextSnapshot(snapshot);
            return;
        }
        const session = document.getElementById("fs-proof-session");
        const state = document.getElementById("fs-proof-state");
        const history = document.getElementById("fs-proof-history");
        const error = document.getElementById("fs-proof-errmsg");
        if (!session || !state || !history || !error) return;
        session.classList.remove("hide");
        document.getElementById("fs-proof-close")?.classList.remove("hide");
        error.innerText = "";
        history.replaceChildren();
        for (const command of snapshot.history) {
            const row = document.createElement("div");
            row.className = "fs-proof-history-row";
            row.textContent = command;
            history.appendChild(row);
        }
        state.replaceChildren();
        if (!snapshot.goals.length) {
            const done = document.createElement("div");
            done.className = "fs-proof-complete";
            done.textContent = TR("无目标，请输入qed结束");
            state.appendChild(done);
        }
        for (let index = snapshot.goals.length - 1; index >= 0; index--) {
            const goal = snapshot.goals[index];
            const block = document.createElement("div");
            block.className = "fs-proof-goal" + (index ? " fs-proof-goal-secondary" : "");
            const title = document.createElement("div");
            title.className = "fs-proof-goal-title";
            title.textContent = index ? `${TR("目标")}${index}：` : TR("当前目标：");
            block.appendChild(title);
            for (const hypothesis of goal.hypotheses) {
                const row = document.createElement("div");
                row.className = "fs-proof-hypothesis";
                row.appendChild(document.createTextNode(hypothesis.proposition
                    ? `${hypothesis.name} : `
                    : hypothesis.kind === "variable" ? `${hypothesis.name} : ${TR("量词变量")}` : hypothesis.name));
                if (hypothesis.proposition) row.appendChild(this.ast2HTML("-", hypothesis.proposition, false));
                block.appendChild(row);
            }
            const target = document.createElement("div");
            target.className = "fs-proof-goal-target";
            target.appendChild(this.ast2HTML("-", goal.target, false));
            block.appendChild(target);
            state.appendChild(block);
        }
        const targetLabel = document.getElementById("fs-proof-target-label");
        if (targetLabel) {
            targetLabel.replaceChildren(document.createTextNode(TR("目标：")));
            targetLabel.appendChild(this.ast2HTML("-", snapshot.theorem, false));
        }
        this.renderInferenceProofTextRecommendations();
        const input = document.getElementById("fs-proof-input") as HTMLTextAreaElement | null;
        input?.classList.remove("hide");
        document.getElementById("fs-proof-begin")?.classList.add("hide");
        this.renderInferenceProofRecommendations();
        input?.focus();
    }
    private parseInferenceProofScript(text: string) {
        return text.split(/\r?\n/).map((raw, index) => {
            const command = raw.trim();
            return { command, lineNumber: index + 1 };
        }).filter(entry => !!entry.command);
    }
    private renderInferenceProofTextSnapshot(
        snapshot: InferenceProofSnapshot,
        error = "",
        errorLine: number | null = null,
        terminal = false
    ) {
        const mode = document.getElementById("fs-proof-text-mode");
        const state = document.getElementById("fs-proof-script-state") as HTMLDivElement | null;
        const errorDiv = document.getElementById("fs-proof-script-error");
        const script = document.getElementById("fs-proof-script") as HTMLTextAreaElement | null;
        if (!mode || !state || !errorDiv || !script) return;
        this.inferenceProofSnapshot = snapshot;
        mode.classList?.remove?.("hide");
        document.getElementById("fs-proof-session")?.classList.add("hide");
        document.getElementById("fs-proof-begin")?.classList.add("hide");
        document.getElementById("fs-proof-close")?.classList.remove("hide");
        if (script.value !== this.inferenceProofScript) {
            script.value = this.inferenceProofScript;
            this.inferenceProofScriptEditor?.refresh();
        }
        errorDiv.replaceChildren();
        if (error) {
            const line = document.createElement("div");
            line.className = "proof-text-line-error";
            line.textContent = errorLine === null
                ? String(error).replace(/^Error:\s*/, "")
                : `第 ${errorLine} 行：${String(error).replace(/^Error:\s*/, "")}`;
            errorDiv.appendChild(line);
        } else if (terminal) {
            const status = document.createElement("div");
            const complete = snapshot.complete;
            status.className = complete ? "proof-text-status" : "proof-text-line-error";
            status.textContent = complete
                ? "qed 已就绪，Ctrl+Enter/执行到光标提交；执行全部运行整页"
                : "qed 未就绪：仍有未完成的证明目标";
            errorDiv.appendChild(status);
        }
        state.replaceChildren();
        if (!snapshot.goals.length) {
            const done = document.createElement("div");
            done.className = "fs-proof-complete";
            done.textContent = TR("无目标，请输入qed结束");
            state.appendChild(done);
        }
        for (let index = snapshot.goals.length - 1; index >= 0; index--) {
            const goal = snapshot.goals[index];
            const block = document.createElement("div");
            block.className = "fs-proof-goal" + (index ? " fs-proof-goal-secondary" : "");
            const title = document.createElement("div");
            title.className = "fs-proof-goal-title";
            title.textContent = index ? `${TR("目标")}${index}：` : TR("当前目标：");
            block.appendChild(title);
            for (const hypothesis of goal.hypotheses) {
                const row = document.createElement("div");
                row.className = "fs-proof-hypothesis";
                row.appendChild(document.createTextNode(hypothesis.proposition
                    ? `${hypothesis.name} : `
                    : hypothesis.kind === "variable" ? `${hypothesis.name} : ${TR("量词变量")}` : hypothesis.name));
                if (hypothesis.proposition) row.appendChild(this.ast2HTML("-", hypothesis.proposition, false));
                block.appendChild(row);
            }
            const target = document.createElement("div");
            target.className = "fs-proof-goal-target";
            target.appendChild(this.ast2HTML("-", goal.target, false));
            block.appendChild(target);
            state.appendChild(block);
        }
        const targetLabel = document.getElementById("fs-proof-target-label");
        if (targetLabel) {
            targetLabel.replaceChildren(document.createTextNode(TR("目标：")));
            targetLabel.appendChild(this.ast2HTML("-", snapshot.theorem, false));
        }
        this.renderInferenceProofTextRecommendations();
    }
    private toggleInferenceProofTextMode() {
        if (!this.inferenceProofAssistant || !this.inferenceProofSnapshot) {
            this.setInferenceProofError(TR("请先启动证明助手"));
            return;
        }
        this.inferenceProofTextMode = !this.inferenceProofTextMode;
        this.inferenceProofTextModePreference = this.inferenceProofTextMode;
        try {
            window.localStorage.setItem(inferenceProofTextModeStorageKey, this.inferenceProofTextMode ? "1" : "0");
        } catch { }
        const textMode = document.getElementById("fs-proof-text-mode");
        const buttonMode = document.getElementById("fs-proof-session");
        const script = document.getElementById("fs-proof-script") as HTMLTextAreaElement | null;
        if (this.inferenceProofTextMode) {
            if (!this.inferenceProofScriptDirty) {
                this.inferenceProofScript = this.inferenceProofSnapshot.history.join("\n");
            }
            if (script) {
                script.value = this.inferenceProofScript;
                this.inferenceProofScriptEditor?.refresh();
            }
            textMode?.classList?.remove?.("hide");
            buttonMode?.classList?.add?.("hide");
            this.renderInferenceProofTextSnapshot(this.inferenceProofSnapshot);
            script?.focus();
        } else {
            textMode?.classList?.add?.("hide");
            buttonMode?.classList?.remove?.("hide");
            this.renderInferenceProofSnapshot(this.inferenceProofSnapshot);
        }
    }
    private scheduleInferenceProofTextReplay() {
        if (!this.inferenceProofTextMode || !this.inferenceProofAssistant) return;
        if (this.inferenceProofTextReplayTimer !== null) window.clearTimeout(this.inferenceProofTextReplayTimer);
        this.inferenceProofTextReplayTimer = window.setTimeout(() => {
            this.inferenceProofTextReplayTimer = null;
            this.replayInferenceProofText(false, true);
        }, 300);
    }
    private replayInferenceProofText(explicitRun: boolean, toCursor = false) {
        if (!this.inferenceProofTextMode || !this.inferenceProofAssistant) return;
        const script = document.getElementById("fs-proof-script") as HTMLTextAreaElement | null;
        if (script) this.inferenceProofScript = script.value;
        const source = toCursor && script ? scriptThroughCaret(script) : this.inferenceProofScript;
        const entries = this.parseInferenceProofScript(source);
        const theorem = this.inferenceProofSnapshot?.theorem ?? this.inferenceProofAssistant.theorem;
        const pageId = this.inferenceProofPageId ?? this.pageStore.activeId;
        let assistant: InferenceProofAssistant;
        let snapshot: InferenceProofSnapshot;
        let errorLine: number | null = null;
        let terminal = false;
        try {
            assistant = new InferenceProofAssistant(this.formalSystem, theorem, {
                pageId,
                ruleNames: this.deductions,
                fastMetaRules: this.formalSystem.fastmetarules,
                allowMcpt: this.metarules.includes("cpt")
            });
            snapshot = assistant.snapshot();
            for (let index = 0; index < entries.length; index++) {
                const entry = entries[index];
                errorLine = entry.lineNumber;
                const qed = /^qed(?:\s+([^\s]+))?$/.exec(entry.command);
                if (qed) {
                    if (index !== entries.length - 1) throw new Error("qed 必须是策略序列的最后一行");
                    terminal = true;
                    if (explicitRun) {
                        this.inferenceProofAssistant = assistant;
                        this.inferenceProofSnapshot = snapshot;
                        const result = this.finishInferenceProof(qed[1] || undefined);
                        if (!result && this.inferenceProofAssistant) {
                            const message = (document.getElementById("fs-proof-errmsg")?.textContent || "qed 执行失败").trim();
                            this.renderInferenceProofTextSnapshot(snapshot, message, errorLine, terminal);
                        }
                        return;
                    }
                    break;
                }
                snapshot = assistant.apply(entry.command);
            }
            this.inferenceProofAssistant = assistant;
            this.inferenceProofSnapshot = snapshot;
            this.renderInferenceProofTextSnapshot(snapshot, "", null, terminal);
            this.persistInferenceProofDraft();
            this.onStateChange();
        } catch (error) {
            if (snapshot) {
                this.inferenceProofAssistant = assistant;
                this.inferenceProofSnapshot = snapshot;
                this.renderInferenceProofTextSnapshot(snapshot, String(error), errorLine);
            } else {
                this.setInferenceProofError(error);
            }
        }
    }
    private setInferenceProofError(error: unknown) {
        const target = document.getElementById("fs-proof-errmsg");
        if (target) target.innerText = String(error).replace(/^Error:\s*/, "");
    }
    applyInferenceProofCommand(command?: string): InferenceProofSnapshot | null {
        if (!this.inferenceProofAssistant || this.inferenceProofBusy) return this.inferenceProofSnapshot;
        const input = document.getElementById("fs-proof-input") as HTMLTextAreaElement | null;
        const value = String(command ?? input?.value ?? "").trim();
        if (!value) {
            this.setInferenceProofError(TR("请输入证明策略"));
            return this.inferenceProofSnapshot;
        }
        // `qed` is a UI action rather than a draft command in the model.  A
        // typed `qed`/`qed name` follows the same transaction as the button.
        const qedCommand = /^qed(?:\s+([^\s]+))?$/.exec(value);
        if (qedCommand) {
            const result = this.finishInferenceProof(qedCommand[1] || undefined);
            // Keep a failed qed command editable so the user can correct a
            // missing goal or macro-name collision without retyping it.
            if (result && input && command === undefined) input.value = "";
            return this.inferenceProofSnapshot;
        }
        this.inferenceProofBusy = true;
        try {
            this.inferenceProofSnapshot = this.inferenceProofAssistant.apply(value);
            if (input && command === undefined) input.value = "";
            this.renderInferenceProofSnapshot(this.inferenceProofSnapshot);
            this.persistInferenceProofDraft();
            this.onStateChange();
            return this.inferenceProofSnapshot;
        } catch (error) {
            // InferenceProofAssistant.apply is transactional.  Keep the input
            // and history intact so a failed command can be corrected in place.
            this.setInferenceProofError(error);
            return this.inferenceProofSnapshot;
        } finally {
            this.inferenceProofBusy = false;
        }
    }
    undoInferenceProof(): InferenceProofSnapshot | null {
        if (!this.inferenceProofAssistant || this.inferenceProofBusy) return this.inferenceProofSnapshot;
        this.inferenceProofBusy = true;
        try {
            this.inferenceProofSnapshot = this.inferenceProofAssistant.undo();
            this.renderInferenceProofSnapshot(this.inferenceProofSnapshot);
            this.persistInferenceProofDraft();
            this.onStateChange();
            return this.inferenceProofSnapshot;
        } catch (error) {
            this.setInferenceProofError(error);
            return this.inferenceProofSnapshot;
        } finally {
            this.inferenceProofBusy = false;
        }
    }
    finishInferenceProof(name?: string): InferenceProofQedResult | null {
        if (!this.inferenceProofAssistant || this.inferenceProofBusy) return null;
        if (this.inferenceProofPageId !== this.pageStore.activeId) {
            this.setInferenceProofError(TR("证明助手只能写入启动时的推理表"));
            return null;
        }
        this.inferenceProofBusy = true;
        try {
            const result = this.inferenceProofAssistant.qed(name);
            if (result.macroName && !this.deductions.includes(result.macroName)) {
                this.addToDeductions(result.macroName);
            }
            this.updatePropositionList(true);
            this.updateDeductionList();
            this.clearPersistedInferenceProofDraft();
            this.closeInferenceProofAssistant();
            this.hintText.innerText = result.macroName
                ? TR("证明完成，已录制宏：") + result.macroName
                : TR("证明完成");
            this.onStateChange();
            return result;
        } catch (error) {
            this.setInferenceProofError(error);
            return null;
        } finally {
            this.inferenceProofBusy = false;
        }
    }
    closeInferenceProofAssistant() {
        this.clearPersistedInferenceProofDraft();
        this.resetInferenceProofUi();
    }
    private resetInferenceProofUi() {
        if (this.inferenceProofTextReplayTimer !== null) {
            window.clearTimeout(this.inferenceProofTextReplayTimer);
            this.inferenceProofTextReplayTimer = null;
        }
        this.inferenceProofAssistant = null;
        this.inferenceProofSnapshot = null;
        this.inferenceProofPageId = null;
        this.inferenceProofBusy = false;
        this.inferenceProofScript = "";
        this.inferenceProofScriptDirty = false;
        document.getElementById("fs-proof-session")?.classList.add("hide");
        document.getElementById("fs-proof-text-mode")?.classList.add("hide");
        document.getElementById("fs-proof-begin")?.classList.remove("hide");
        document.getElementById("fs-proof-close")?.classList.add("hide");
        const input = document.getElementById("fs-proof-input") as HTMLTextAreaElement | null;
        if (input) input.value = "";
        const script = document.getElementById("fs-proof-script") as HTMLTextAreaElement | null;
        if (script) {
            script.value = "";
            this.inferenceProofScriptEditor?.refresh();
        }
        const name = document.getElementById("fs-proof-name") as HTMLInputElement | null;
        if (name) name.value = "";
        const state = document.getElementById("fs-proof-state");
        const history = document.getElementById("fs-proof-history");
        if (state) state.replaceChildren();
        if (history) history.replaceChildren();
        this.renderInferenceProofRecommendations();
        this.setInferenceProofError("");
    }
    clearPListMasked() {
        this.propositionList.querySelectorAll("div.p-match-failed").forEach(e => e.classList.remove("p-match-failed"));
    }
    canExpandInferenceOffThread(): boolean {
        return typeof Worker !== "undefined"
            && this.inferenceProofAssistant === null
            && this.cmd.cmdBuffer[0] !== "entr";
    }

    async expandInferenceOffThread(target: InferenceWorkerTarget): Promise<void> {
        if (!this.canExpandInferenceOffThread()) throw new Error(TR("当前推理状态不能后台展开"));
        const saves = new SavesParser(this.creative);
        const before = this.inferenceWorkerFingerprint(saves);
        const save = this.inferenceWorkerSave(saves);
        const client = this.inferenceWorkerClient ??= new InferenceWorkerClient();
        const result = await client.expand({
            save,
            creative: this.creative,
            fastMetaRules: this.formalSystem.fastmetarules,
            metarules: [...this.metarules],
            target
        });
        if (before !== this.inferenceWorkerFingerprint(saves)) {
            throw new Error(TR("推理表在后台展开期间发生变化，请重新展开"));
        }
        this.applyInferenceWorkerResult(result, saves);
    }

    cancelInferenceExpansion() {
        this.inferenceWorkerClient?.terminate();
    }

    private inferenceWorkerFingerprint(saves: SavesParser): string {
        const pages = this.pageStore.pages.map(page => ({
            id: page.id,
            name: page.name,
            propositions: page.propositions.map(proposition => saves.serializeProposition(proposition))
        }));
        return JSON.stringify({ activeId: this.pageStore.activeId, pages });
    }

    private inferenceWorkerSave(saves: SavesParser): string {
        const parsed = JSON.parse(saves.serialize(this)) as { data?: any[] };
        const pagePayload = parsed.data?.[7];
        if (pagePayload?.pages) {
            for (const page of pagePayload.pages) page.command = { input: "", buffer: [] };
        }
        return JSON.stringify(parsed);
    }

    private applyInferenceWorkerResult(result: InferenceWorkerResult, saves: SavesParser): void {
        const parsed = JSON.parse(result.save) as { data?: any[] };
        if (!Array.isArray(parsed.data)) throw new Error(TR("推理层 Worker 返回的存档无效"));
        const restored = saves.deserializeArr(initFormalSystem(this.creative).fs, parsed.data).fs;
        for (const [name, encoded] of Object.entries(result.deductions)) {
            delete restored.deductions[name];
            saves.deserializeDeduction(name, restored, encoded as any);
        }
        const fastMetaRules = this.formalSystem.fastmetarules;
        this.formalSystem = restored;
        this.formalSystem.fastmetarules = fastMetaRules;
        this.pageStore = restored.inferencePages;
    }

    getProps() {
        return this.cmd.cmdBuffer[0] === "entr" ? this.cmd.cmdBuffer[2] ?? this.formalSystem.propositions : this.formalSystem.propositions
    }
    /** Gate matching may inspect every persistent inference page, not only the active one. */
    hasPropositionForGate(ast: AST): boolean {
        for (const page of this.pageStore.pages) {
            // A #p gate is intentionally unavailable while the page contains
            // hypotheses.  Hypotheses are stored as the leading rows, so the
            // first row is the page-level marker for this rule.
            if (!page.propositions[0]?.from) continue;
            if (page.propositions.some(p => astmgr.equal(p.value, ast))) return true;
        }
        return false;
    }
    updateSysFnList() {
        if (this.skipRendering) return;
        if (this.unlockedSysRulePanel) this.sysFnList.parentElement.parentElement.classList.remove("hide");
        let i = 0;
        this.updateGuiList("m", this.sysfns.map(e => ({ value: e[0] })), this.sysFnList, (p) => true, (p, itInfo, it, pname) => {
            let node;
            let isItem = false;
            let errmsg = "";
            const [ast, info] = this.sysfns[i++];
            let sf = astmgr.clone(ast);
            try {
                this.formalSystem.assert.expand(sf, true);
                node = sf;
            } catch (e) {
                sf = astmgr.clone(ast);
                try {
                    this.formalSystem.assert.expand(sf, true);
                    isItem = true;
                    node = sf;
                } catch (e) {
                    errmsg = e;
                }
            }
            this.addSpan(it, " ⟹ ");
            const html = node ? this.ast2HTML("d", node, isItem) : this.addSpan(it, errmsg).classList.add("error-color");
            if (html) it.appendChild(html);
            itInfo[0].innerText = info;
        }, true, this.sysfns.map(e => e[2]));
    }
    updatePropositionList(refresh?: boolean) {
        if (this.skipRendering) return;
        this.updateGuiList("p", this.formalSystem.propositions, this.propositionList, (p) => true, (p, itInfo, it, pname) => {
            itInfo[0].addEventListener("click", () => {
                if (this.cmd.cmdBuffer.length === 0) {
                    this.cmd.clearCmdBuffer();
                    this.hintText.innerText = TR("命令：");
                } else if (this.cmd.cmdBuffer[0] !== "entr") return;
                const from = p.from;
                const cmd = (from?.assistant ?
                    // Assistant proofs carry their recipe on the step and do
                    // not have a rule name that can be entered with `d`.
                    `entr ${pname}`
                    : from ?
                    ["d", from.deductionIdx, ...from.conditionIdxs,
                        ...from.replaceValues.map(v => this.cmd.astparser.stringifyTight(v))
                    ].join(" ")
                    : ("hyp " + this.cmd.astparser.stringifyTight(p.value))
                );
                this.cmd.replaceActionInputFromClick(cmd);
            });
            if (!p.from) {
                itInfo[0].innerText = TR("假设");
                return;
            }
            this.stringifyDeductionStep(itInfo[0], p.from);
            it.addEventListener("mouseover", () => {
                p.from.conditionIdxs.forEach(idx => {
                    const el = document.querySelector(`#prop-list .idx:nth-child(${(idx + 1) * 8 - 7})`);
                    if (el) el.classList.add("p-highlighted-before");
                });
                const pidx = Number(pname.slice(1));
                for (let i = pidx + 1; i < this.formalSystem.propositions.length; i++) {
                    const from = this.formalSystem.propositions[i]?.from;
                    if (!from) continue;
                    if (!from.conditionIdxs.includes(pidx)) continue;
                    const el = document.querySelector(`#prop-list .idx:nth-child(${(i + 1) * 8 - 7})`);
                    if (el) el.classList.add("p-highlighted-after");
                }
            });
            it.addEventListener("mouseout", () => {
                for (let i = 0; i < this.formalSystem.propositions.length; i++) {
                    const el = document.querySelector(`#prop-list .idx:nth-child(${(i + 1) * 8 - 7})`);
                    if (!el) continue;
                    el.classList.remove("p-highlighted-before");
                    el.classList.remove("p-highlighted-after");
                }
            });
        }, refresh);
        const usedPs = new Set<number>();
        for (let pidx = this.deductions.length - 1; pidx >= 0; pidx--) {
            const from = this.formalSystem.propositions[pidx]?.from;
            if (!from) continue;
            for (const cidx of from.conditionIdxs) {
                usedPs.add(cidx);
            }
        }
        for (let i = 0; i < this.formalSystem.propositions.length; i++) {
            if (!usedPs.has(i)) {
                for (let j = 1; j < 8; j++) {
                    const el = document.querySelector(`#prop-list div:nth-child(${(i + 1) * 8 - 7 + j})`);
                    if (el) el.classList.add("p-unused");
                }
            } else {
                for (let j = 1; j < 8; j++) {
                    const el = document.querySelector(`#prop-list div:nth-child(${(i + 1) * 8 - 7 + j})`);
                    if (el) el.classList.remove("p-unused");
                }
            }
        }
        this.draggerP.attachIdxListener();
    }
    updateDeductionList() {
        if (this.skipRendering) return;
        const types = new Set<string>;
        const ds = this.deductions.map(d => {
            try {
                const k = d.startsWith('< f >') ? null : this.formalSystem.deductions[d] || this.formalSystem.generateDeduction(d);
                return k;
            } catch (e) { return null; }
        });
        for (const d of ds) {
            if (!d) continue;
            types.add(d.from);
            if (d.from.endsWith("*")) types.add("添加的规则");
        }
        document.querySelectorAll("input[name='show-d']").forEach((sd: HTMLInputElement) => {
            const from = (sd.parentNode as HTMLElement).getAttribute("data-tr");
            if (types.has(from)) sd.parentElement.classList.remove("hide"); else sd.parentElement.classList.add("hide");
        });

        const from = this.deductionList.offsetHeight;

        this.drawDeductionList(ds, this.deductionList,
            (p, itInfo, it) => {
                itInfo[0].innerText = TR(p.from).replace(/s$/, "").replaceAll("<", "&lt;").replaceAll(">", "&gt;") + (p.steps?.length || p.deferredKind === "cpt" || p.deferredKind === "assistant" ? TR("[宏]") : "");
            }, this.deductions
        );

        const to = this.deductionList.offsetHeight;
        if (to > from) {
            this.deductionList.style.height = from + 'px';
            requestAnimationFrame(() => {

                this.deductionList.style.height = to ? to + 'px' : "auto";
            });
            const reset = () => {
                this.deductionList.style.height = 'auto';
                this.deductionList.removeEventListener('transitionend', reset);
            };
            this.deductionList.addEventListener('transitionend', reset);
        }
        this.draggerD.attachIdxListener();
        this.renderInferenceProofRecommendations();
    }
    updateMetaRuleList(refresh?: boolean) {
        if (this.skipRendering) return;
        this.updateGuiList("m", Object.fromEntries(this.metarules.map(e => [e, this.formalSystem.metaRules[e]])), this.metaRuleList, (p, idx) => this.metarules.includes(idx), (p, itInfo, it) => {
            itInfo[0].innerHTML = TR(p.from).replaceAll("<", "&lt;").replaceAll(">", "&gt;");
        }, refresh, this.metarules.map(e => "m" + e));
        this.draggerM.attachIdxListener();
        this.renderInferenceProofRecommendations();
    }
    private scanDeductionFolderScope(targets: string[]) {
        const fStack: [string, number, number][] = [];
        const res: { [n: string]: [string, number, number][] } = {};
        for (let i = 0; i < this.deductions.length; i++) {
            while (true) {
                const last = fStack.pop();
                if (!last) break;
                if (last[2] >= i) {
                    fStack.push(last);
                    break;
                }
            }
            const name = this.deductions[i];
            if (name.startsWith("< f >")) {
                const [fname, flength, fuuid, fstate] = name.slice(5).split("::");
                fStack.push([fuuid, Number(flength), i + Number(flength)]);
            }
            if (targets.includes(name)) {
                res[name] = fStack.slice(0);
            }

        }
        return res;
    }
    private setDeductionFolderCount(fuuid: string, count: (number) => number) {
        const idx = this.deductions.findIndex(d => d.startsWith("< f >") && d.split("::")[2] === fuuid);
        if (idx === -1) return false;
        const n = this.deductions[idx].split("::");
        n[1] = String(count(Number(n[1])));
        this.deductions[idx] = n.join("::");
    }
    removeDeductionFolderCount(name: string[]) {
        const scope = this.scanDeductionFolderScope(name);
        for (const s of Object.values(scope)) {
            for (const [uuid] of s) {
                this.setDeductionFolderCount(uuid, c => c - 1);
            }
        }
    }
    private drawDeductionList(
        logicArray: Deduction[], list: HTMLElement,
        setInfo: (term: Deduction, itInfo: HTMLElement[], it: HTMLElement, label: string) => void,
        customIdx: string[]
    ) {
        this.onStateChange();
        while (list.lastChild) {
            list.removeChild(list.lastChild);
        }
        const fStack: [string, number, number][] = [];
        const values = Object.values(logicArray);
        const targetLength = values.length;
        for (let listIdx = 0; listIdx < targetLength; listIdx++) {
            const p = values[listIdx];
            const pname = customIdx[listIdx];
            let skipRendering = false;
            while (true) {
                const last = fStack.pop();
                if (!last) break;
                if (last[2] >= listIdx) {
                    fStack.push(last);
                    break;
                }
            }
            for (const s of fStack) {
                if (s[0] === "+") { skipRendering = true; break; }
            }
            if (!skipRendering) {
                const itIdx = document.createElement("div");
                list.appendChild(itIdx);
                itIdx.classList.add("idx");
                itIdx.innerText = pname;
                const itVal = document.createElement("div");
                list.appendChild(itVal);
                this.addSpan(itVal, "│".repeat(fStack.length)).className = "dir-bar";
                if (p) {
                    itVal.classList.add("val");

                    itVal.appendChild(this.ast2HTML(pname, p.value, false));

                    const infoArr = [];
                    for (let i = 0; i < 6; i++) {
                        const itInfo = document.createElement("div");
                        list.appendChild(itInfo);
                        itInfo.className = "info";
                        infoArr.push(itInfo);
                    }
                    setInfo(p, infoArr, itVal, pname);

                    itVal.addEventListener("click", () => {
                        const inserted = this.cmd.astparser.stringify(p.value);
                        this.cmd.onClickSubAst(pname, inserted);
                    });
                } else {
                    itIdx.classList.add("dir-idx");
                    itVal.classList.add("dir-val");
                    const [fname, flength, fuuid, fstate] = pname.slice(5).split("::");
                    const dir = this.addSpan(itVal, fname.startsWith("#") ? TR(fname.slice(1)) : fname);
                    dir.classList.add(fstate === "+" ? "dir-close" : "dir-open");
                    dir.classList.add("dir-val");
                    for (let i = 0; i < 6; i++) {
                        const itInfo = document.createElement("div");
                        itInfo.classList.add("dir-val");
                        itInfo.classList.add("dir-info");
                        list.appendChild(itInfo);
                        if (i) continue;

                        this.addSpan(itInfo, " ➕ ").addEventListener("click", e => {
                            if (!this.cmd.cmdBuffer.length) {
                                for (let i = this.deductions.indexOf(pname), j = 0; j < Number(pname.split("::")[1]); i++, j++) {
                                    const d = this.deductions[i];
                                    if (d.startsWith("< f >") && d.endsWith("-")) {
                                        this.deductions[i] = d.slice(0, -1) + "+";
                                    }
                                }
                            }
                            this.updateDeductionList();

                        });
                        this.addSpan(itInfo, " ➖ ").addEventListener("click", e => {
                            if (!this.cmd.cmdBuffer.length) {
                                for (let i = this.deductions.indexOf(pname), j = 0; j < Number(pname.split("::")[1]); i++, j++) {
                                    const d = this.deductions[i];
                                    if (d.startsWith("< f >") && d.endsWith("+")) {
                                        this.deductions[i] = d.slice(0, -1) + "-";
                                    }
                                }
                            }
                            this.updateDeductionList();

                        });
                        this.addSpan(itInfo, " ✏️ ").addEventListener("click", e => {
                            if (!this.cmd.cmdBuffer.length) {
                                this.cmd.cmdBuffer.push("op-dir", "rename", fuuid);
                                this.cmd.execCmdBuffer();
                            }
                        });
                        this.addSpan(itInfo, " 🗑️ ").addEventListener("click", e => {
                            if (!this.cmd.cmdBuffer.length) {
                                if (!confirm(TR("该操作将删除文件夹，并将里面的内容散列在上级目录中，确定要删除<") + (pname.slice(5).split("::")[0]) + TR(">吗？"))) return;
                                this.deductions.splice(this.deductions.indexOf(pname), 1);
                                this.removeDeductionFolderCount([pname]);
                            }
                            this.updateDeductionList();
                        });
                    }
                    itVal.addEventListener("click", () => {
                        if (this.deductions[listIdx].endsWith("+")) {
                            this.deductions[listIdx] = this.deductions[listIdx].slice(0, -1) + "-";
                        } else {
                            this.deductions[listIdx] = this.deductions[listIdx].slice(0, -1) + "+";
                        }
                        this.updateDeductionList();
                    });
                }
            }
            if (!p) {
                const [fname, flength, fuuid, fstate] = pname.slice(5).split("::");
                fStack.push([fstate, listIdx, listIdx + Number(flength)]);
            }
        }
        list.scroll({ top: list.scrollHeight });
    }
    tree2HTML(tree: RuleTree): HTMLElement {
        const span = document.createElement("span");
        span.classList.add("rule-node");

        if (tree.length === 1) {
            span.textContent = tree[0];
            span.classList.add("rule-token");
            if (tree[0].startsWith("$$")) {
                span.classList.add("replvar");
                span.classList.remove("rule-token");
            }
        } else if (tree[0][0] === "#") {
            const hash = document.createElement("span");
            hash.textContent = tree[0];
            span.appendChild(hash);
            for (let i = 1; i < tree.length; i++) {
                const comma = document.createElement("span");
                comma.textContent = ",";
                span.appendChild(comma);
                span.appendChild(this.tree2HTML(tree[i] as RuleTree));
            }
        } else if (tree[0] === ":") {
            for (let i = 1; i < tree.length; i++) {
                const sep = document.createElement("span");
                sep.textContent = i === tree.length - 1 ? "," : ":";
                span.appendChild(sep);
                span.appendChild(this.tree2HTML(tree[i] as RuleTree));
            }
        } else if (tree.length === 2) {
            const first = document.createElement("span");
            first.textContent = tree[0];
            span.appendChild(first);
            span.appendChild(this.tree2HTML(tree[1] as RuleTree));
        }
        const spans = Array.from(span.childNodes) as HTMLSpanElement[];
        for (const node of spans.filter(n => (!n.classList) || !n.classList.contains("rule-node"))) {
            node.addEventListener('mouseover', ev => {
                for (const node of spans) {
                    node.classList.add("rule-highlighted");
                }
            });
            node.addEventListener('mouseout', ev => {
                for (const node of spans) {
                    node.classList.remove("rule-highlighted");
                }
            });
        }
        return span;
    }
    stringifyDeductionStep(dom: HTMLSpanElement, step: DeductionStep) {
        if (!dom) {
            const name = step.assistant || step.deductionIdx === DEFERRED_ASSISTANT_STEP
                ? TR("证明助手") : step.deductionIdx;
            return `&nbsp;${name} ${step.conditionIdxs.join(",")}`;
        }
        const span = this.addSpan(dom, "&nbsp;", true);
        if (step.assistant || step.deductionIdx === DEFERRED_ASSISTANT_STEP) {
            span.appendChild(document.createTextNode(TR("证明助手")));
        } else {
            const didx = this.tree2HTML(this.formalSystem.getDeductionTokens(step.deductionIdx));
            span.appendChild(didx);
        }
        this.addSpan(span, " ");
        let firstTerm = true;
        for (const p of step.conditionIdxs) {
            if (!firstTerm) this.addSpan(span, ",");
            firstTerm = false;
            const sp = this.addSpan(span, String(p));
            sp.classList.add("rule-cond");
            sp.addEventListener("mouseover", ev => {
                const el = document.querySelector(`#prop-list .idx:nth-child(${(p + 1) * 8 - 7})`);
                if (el) el.classList.add("p-highlighted-before");
            });
            sp.addEventListener("mouseout", ev => {
                const el = document.querySelector(`#prop-list .idx:nth-child(${(p + 1) * 8 - 7})`);
                if (el) el.classList.remove("p-highlighted-before");
            });
        }
    }
    addToDeductions(name: string, after?: string) {
        const oldpos = this.deductions.indexOf(name);
        // delete
        if (oldpos !== -1) {
            if (after === name) return; // x=S(x), aborted
            if (after === this.deductions[oldpos - 1]) return; // identity
            this.deductions.splice(oldpos, 1);
        }
        // insert
        if (!after) {
            this.deductions.push(name);
            this.updateDeductionList();
            return;
        }
        const pos = this.deductions.indexOf(after);
        if (pos === -1) {
            this.deductions.push(name);
        } else {
            const scope = this.scanDeductionFolderScope([after]);
            for (const s of Object.values(scope)) {
                for (const [uuid] of s) {
                    this.setDeductionFolderCount(uuid, c => c + 1);
                }
            }
            this.deductions.splice(pos + 1, 0, name);
        }
        this.updateDeductionList();
    }
    getDeduction(id: string): Deduction {
        if (id === ".") return this.getDeduction(this.cmd.lastDeduction);
        // if cuv is locked, can't use cmp and vmp
        if ("cuv".includes(id[0]) && !this.formalSystem.fastmetarules.includes(id[0])) {
            if (id[0] === "v" && this.formalSystem.fastmetarules.includes("q")) {
                if (id.match(/^v*mp$/)) return null;
            } else return null;
        }
        const tokens = [];
        this.formalSystem.getAtomDeductionTokens(id, tokens);
        for (const it of tokens) {
            if (this.deductions.includes(it)) continue;
            // if .XX is locked, can't use it
            if (it[0] === "." && !(
                this.formalSystem.fastmetarules.includes("#") && (
                    this.formalSystem.generateNatLiteralOp(it) || this.formalSystem.generateNatLiteralIsNat(it)
                ) ||
                (this.formalSystem.fastmetarules.includes("Z") && (this.formalSystem.generateZLiteralIsZ(it) || this.formalSystem.generateZLiteralOp(it)))

            )) return null;
            if (it[0] === "a" || it[0] === "d") {
                if (!(
                    (this.formalSystem.fastmetarules.includes("#") && this.formalSystem.generateNatLiteralDef(it)) ||
                    (this.formalSystem.fastmetarules.includes("z") && this.formalSystem.generateZLiteralDef(it)) ||
                    (this.formalSystem.fastmetarules.includes("R") && this.formalSystem.generateRLiteralDef(it)) ||
                    (this.formalSystem.fastmetarules.includes("Q") && this.formalSystem.generateQLiteralDef(it))
                ))
                    return null;
            }
        }

        try {
            return this.formalSystem.generateDeduction(id);
        } catch (e) { return null; }
    }
}


